<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo $this->title; ?></title>

    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/styles.css?2" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/site.webmanifest">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

</head>

<body>

<nav class="navbar navbar-inverse">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Меню сайта</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="/images/logo.png" alt=""></a>
        </div>

        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav pull-right">
                <li><a href="/setka/">Турнирная сетка</a></li>
                <li><a href="/raspisanie/">Расписание матчей</a></li>
            </ul>

            <form class="navbar-form" role="search">
                <div class="wrapper">
                    <div>
                        <button><img src="/images/search-icon.png" alt=""></button>
                        <input type="text" class="form-control" placeholder="Поиск">
                    </div>
                </div>
            </form>

        </div>
    </div>
</nav>


<? if (strpos($_SERVER['REQUEST_URI'], '/login/') === false): ?>
<div class="section section-buttons">
    <div class="container">
        <a href="/">Прямая трансляция</a>
        <a href="/future/">Будущие матчи</a>
        <a href="/archive/">Архив матчей</a>
    </div>
</div>
<? endif ?>



<?php echo $this->layout()->content; ?>




<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4 logo-persik">
                <img src="/images/logo_persik.png" alt="">
            </div>
            <div class="col-md-4 contacts">
                <img src="/images/icon-letter.png" alt=""> info@persik.tv
            </div>
            <div class="col-md-2 logo-volk">
                <img src="/images/volk.png" alt="">
            </div>
        </div>
    </div>
</footer>


<script src="/js/jquery.js"></script>
<script src="/js/bootstrap.js"></script>
</body>
</html>


