<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo $this->title; ?></title>

    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/styles.css?20180627" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/site.webmanifest">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <script src="/js/jquery.js"></script>
    <script charset="UTF-8" src="//cdn.sendpulse.com/9dae6d62c816560a842268bde2cd317d/js/push/7d8e4b4734862d692c51d9bd46cd7225_1.js" async></script>
    
</head>

<body>

<nav class="navbar navbar-inverse">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Меню сайта</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="/images/logo.png" alt=""></a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">

            <ul class="nav navbar-nav">
                <li><a href="/setka/">Турнирная сетка</a></li>
                <li><a href="/raspisanie/">Расписание матчей</a></li>
            </ul>

            <form class="navbar-form" role="search">
                <div class="wrapper">
                    <div>
                        <button><img src="/images/search-icon.png" alt=""></button>
                        <input type="text" class="form-control" placeholder="Поиск">
                    </div>
                </div>
            </form>

        </div>
    </div>
</nav>


<?php if (strpos($_SERVER['REQUEST_URI'], '/login/') === false): ?>
<div class="section section-buttons">
    <div class="container">
        <a href="/">Прямая трансляция</a>
        <a href="/future/">Будущие матчи</a>
        <a href="/archive/">Архив матчей</a>
    </div>
</div>
<?php endif ?>



<?php echo $this->layout()->content; ?>


<div class="footer-spacer"></div>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-8 txt">
                <img src="/images/logo_persik.png" alt="" class="logo-persik ">
                <img src="/images/icon-letter.png" alt="" class="icon-contacts"> info@persik.tv
            </div>
            <div class="col-xs-6 col-sm-4 logo-volk">
                <img src="/images/volk.png" alt="">
            </div>
        </div>
    </div>
</footer>


<script src="/js/bootstrap.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter49299667 = new Ya.Metrika2({
                    id:49299667,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/tag.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks2");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/49299667" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->


</body>
</html>
