                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <table width="100%" border="0">
                                            <tr>
                                                <td width="*">
                                                    &nbsp;
                                                </td>
                                                <td width="250">
                                                    <div style="font-size: 16px; font-family:'Open Sans', Arial, Helvetica, sans-serif; line-height: 1.5em; padding-right:20px; padding-top: 50px;">
                                                        <strong>Мы Вас любим,</strong><br>
                                                        <strong>Команда Persik</strong><br> 
                                                        <table border="0" style="font-size: 13px; line-height: 1.3em; margin-top: 10px;">
                                                            <tr>
                                                                <td width="22"><img src="http://persik.by/templates/default/images/email/clock-small.png" style="vertical-align: middle;"></td>
                                                                <td>ежедневно с 10:00 до 22:00</td>
                                                            <tr>
                                                            <tr>
                                                                <td><img src="http://persik.by/templates/default/images/email/phone-small.png" style="vertical-align: middle;"></td>
                                                                <td><a href="tel:+375173361111" style="color: #000; text-decoration: none">+375 17 336-11-11</a></td>
                                                            <tr>
                                                            <tr>
                                                                <td><img src="http://persik.by/templates/default/images/email/mobile-small.png" style="vertical-align: middle;"></td>
                                                                <td><a href="tel:+375293361100" style="color: #000; text-decoration: none">+375 29 336-11-00</a></td>
                                                            <tr>
                                                            <tr>
                                                                <td><img src="http://persik.by/templates/default/images/email/mail-small.png" style="vertical-align: middle;"></td>
                                                                <td><a href="mailto:info@persik.by" style="color: #000; text-decoration: none">info@persik.by</a></td>
                                                            <tr>
                                                        </table>
                                                        <div style="font-size: 14px; margin-top: 10px;">
                                                            <a class="vk" href="https://vk.com/persiktv" target="_blank"><img height="32" src="http://persik.tv/images/vk-icon.png" width="32"></a>
                                                            <a class="fb" href="https://www.facebook.com/pages/Persikby/842229285816183" target="_blank"><img height="32" src="http://persik.tv/images/fb-icon.png" width="32"></a>
                                                        </div>
                                                    </div>
                                                    <br> 
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="space" height="50" style="text-align: center;"><a href="http://persik.by" target="_blank"><img alt="" src="https://media.persik.by/email/footer.jpg"></a></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>