<div class="section section-thumbs">
    <div class="container">
        <div class="row">

            <?php foreach ($this->items as $item): ?>
                <div class="col-sm-4">
                    <a href="<?php echo $item['url']?>"><img src="<?php echo $item['thumb']?>" alt=""></a>
                    <span><a href="<?php echo $item['url']?>"><?php echo $item['cmd1']['name_ru']?> - <?php echo $item['cmd2']['name_ru']?>, <?=$item['date_ru']?></a></span>
                </div>
            <?php endforeach ?>


        </div>


    </div>
</div>
