<div class="section section-thumbs">
    <div class="container">
        <div class="row">

            <? foreach ($this->items as $item): ?>
                <div class="col-md-4">
                    <a href="<?=$item['url']?>"><img src="<?=$item['thumb']?>" alt=""></a>
                    <span><a href="<?=$item['url']?>"><?=$item['cmd1']['name_ru']?> - <?=$item['cmd2']['name_ru']?>, <?=$item['datetime_ru']?> <?//=$item['channel_id']?></a></span>
                </div>
            <? endforeach ?>


        </div>


    </div>
</div>
