<div class="section section-thumbs">
    <div class="container">
        <div class="row">

            <?php if ($this->itemsNow):
                foreach ($this->itemsNow as $item): ?>
                <div class="col-md-4">
                    <a href="<?php echo $item['url']?>"><img src="<?php echo $item['thumb']?>" alt=""></a>
                    <span><a href="<?php echo $item['url']?>"><?php echo $item['cmd1']['name_ru']?> - <?php echo $item['cmd2']['name_ru']?>, <?php echo $item['date_ru']?></a></span>
                </div>
                <?php endforeach;
            else: ?>
                <div class="text-center">Сейчас трансляций нет</div>
            <?php endif ?>

        </div>

        <hr>

    </div>
</div>


<div class="section section-thumbs">
    <div class="container">
        <div class="row">
            <div class="h-green-square"></div>
            <h2>Будущие трансляции</h2>
        </div>
        <div class="row">

            <?php foreach ($this->itemsFuture as $item): ?>
            <div class="col-md-4">
                <a href="<?php echo $item['url']?>"><img src="<?php echo $item['thumb']?>" alt=""></a>
                <span><a href="<?php echo $item['url']?>"><?php echo $item['cmd1']['name_ru']?> - <?php echo $item['cmd2']['name_ru']?>, <?php echo $item['datetime_ru']?></a></span>
            </div>
            <?php endforeach ?>

        </div>

        <div class="row button-more">
            <a href="/future/">Еще</a>
        </div>

        <hr>

    </div>
</div>


<div class="section section-thumbs">
    <div class="container">
        <div class="row">
            <div class="h-green-square"></div>
            <h2>Архив 5 дней</h2>
        </div>

        <div class="row">

            <?php foreach ($this->itemsArchive as $item):?>
                <div class="col-md-4">
                    <a href="<?php echo $item['url']?>"><img src="<?php echo $item['thumb']?>" alt=""></a>
                    <span><a href="<?php echo $item['url']?>"><?php echo $item['cmd1']['name_ru']?> - <?php echo $item['cmd2']['name_ru']?>, <?php echo $item['datetime_ru']?></a></span>
                </div>
            <?php endforeach ?>

        </div>

        <div class="row button-more">
            <a href="/archive/">Еще</a>
        </div>

    </div>
</div>
