
<div class="section section-login">
    <div class="container">
        <div class="row">

            <div class="col-md-8 col-md-offset-2">


                <div>
                    <img src="/images/cup2018.png" class="cup" alt="">
                </div>

                <h2>ВСЕ ТРАНСЛЯЦИИ МАТЧЕЙ ЧЕМПИОНАТА МИРА ПО ФУТБОЛУ <!--<br>-->
                    НА RUSSIA2018.PERSIK.TV</h2>

                <h1>Ничего лишнего - только Футбол!</h1>

                <p>
                    Для АБСОЛЮТНО БЕСПЛАТНОГО просмотра ВСЕХ трансляций матчей - <br>
                    оставьте свой e-mail, мы вышлем Вам ДОСТУП к ресурсу.
                </p>

                <div class="form-email">
                    <form action="" method="post">

                        <div class="email-bg">
                            <span class="email-txt">E-mail</span>
                            <input type="text" name="email" class="form-control">
                        </div>

                        <? if ($this->error): ?>
                        <div class="error">
                            <?=$this->error?>
                        </div>
                        <? endif ?>

                        <div class="button">
                            <button type="submit" class="btn btn-default">Бесплатный доступ</button>
                        </div>

                    </form>
                </div>

                <p class="notes">
                    <img src="/images/green-square.png" alt="">
                    ЕСЛИ ВЫ УЖЕ ЗАРЕГИСТРИРОВАНЫ В СИСТЕМЕ или ЯВЛЯЕТЕСЬ ПОЛЬЗОВАТЕЛЕМ СЕРВИСА PERSIK - то ДЛЯ ВХОДА введите СВОЙ ЛОГИН (Email) - и наслаждайтесь просмотром!
                </p>


            </div>


        </div>
    </div>
</div>