<div class="section section-login">
    <div class="container">
        <div class="row">

            <div class="col-md-8 col-md-offset-2">


                <div>
                    <img src="/images/cup2018.png" class="cup" alt="">
                </div>

                <div class="col-md-10 col-md-offset-1 success">
                    <h1>Оле! Оле! Оле! Оле!</h1>
                    <div class="big">Будем смотреть Футбол вместе!</div>
                    <div class="big">Осталось только подтвердить регистрацию.</div>
                    <div class="txt">Пройдите в почту, нажмите кнопку “ПОДТВЕРДИТЬ” <br>
                        - и смотрите все трансляции матчей Чемпионата Мира по футболу <br>
                        абсолютно бесплатно на russia2018.persik.tv</div>
                </div>


            </div>
        </div>
    </div>