<div class="section section-match">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <div class="gazon">
                    <h1>
                        <?php echo $this->cmd1['name_ru']?> <img src="<?php echo $this->cmd1['img']?>" alt="">
                        &mdash;
                        <?php echo $this->cmd2['name_ru']?> <img src="<?php echo $this->cmd2['img']?>" alt="">
                    </h1>
                    <br>
                    <?/*<div class="when">25 июня 2018, понедельник, в 17:00 (мск)</div>*/?>
                    <div class="when"><?php echo $this->item['datetime_ru']?></div>
                    <div class="stage">Групповой этап ЧМ-2018</div>
                    <?/*<div class="where">Самара, стадион «Самара Арена»</div>*/?>
                    <div class="where"><?php echo $this->item['city']?></div>

                    <div class="player-wrapper">
                        <?php if ($this->item['is_online'] or $this->item['is_archive']): ?>

                            <div id="player"></div>

                            <script src="/js/clappr.min.js"></script>

                            <script>
                                $(document).ready(function () {
                                    var player = new Clappr.Player({
                                        parentId: "#player",
    //                                    source: "https://bamper.by/upload/futbik11.mp4",
                                        source: "<?php echo $this->stream_url?>",
                                        width: 600,
                                        height: 339,
                                        autoPlay: true
    //                                    autoPlay: false
                                    });
                                    Clappr.Log.setLevel(0);
                                });
                            </script>

                        <?php endif ?>
                    </div>

                </div>

            </div>
        </div>


        <?/*
        <div class="row">
            <div class="col-md-12 history">

                <div class="h-green-square"></div>
                <h2>История встреч</h2>

                <p>
                    До матча в рамках группового этапа финальной стадии ЧМ-2018 команды Уругвая и России встречались один раз — это была товарищеская игра в 2012 году, которая прошла в Москве и завершилась вничью со
                    счётом 1:1. По состоянию на июнь 2018 года сборная Уругвая занимает 14-е место в международном рейтинге ФИФА, а сборная России — 70-е. При этом чемпионами мира уругвайцы в своей истории становились
                    дважды — в 1930-м и 1950-м годах, а ЧМ-2018 станет 13-м первенством, в котором команда примет участие.
                </p>

            </div>
        </div>


        <div class="row">
            <div class="col-md-12 sostav">

                <div class="h-green-square"></div>
                <h2>Составы команд на игру</h2>
                <div class="row">

                    <div class="col-md-6 sostav-left">
                        <img src="/images/flags/russia.svg" alt="">
                        <ul>
                            <li>Главный тренер</li>
                            <li>Станислав Черчесов</li>
                        </ul>

                        <ul>
                            <li>Стартовый состав</li>
                            <li>Андрей Лунёв</li>
                            <li>Виктор Васин</li>
                            <li>Георгий Джикия</li>
                            <li>Фёдор Кудряшов</li>
                            <li>Юрий Жирков</li>
                            <li>Игорь Смольников</li>
                            <li>Алан Дзагоев</li>
                            <li>Далер Кузяев</li>
                            <li>Денис Глушаков</li>
                            <li>Алексей Миранчук</li>
                            <li>Фёдор Смолов</li>
                        </ul>

                        <ul>
                            <li>Запасные</li>
                            <li>Владимир Габулов</li>
                            <li>Роман Нойштедтер</li>
                            <li>Илья Кутепов</li>
                            <li>Константин Рауш</li>
                            <li>Дмитрий Комбаров</li>
                            <li>Антон Миранчук</li>
                            <li>Александр Ерохин</li>
                            <li>Владислав Игнатьев</li>
                            <li>Антон Швец</li>
                            <li>Антон Заболотный</li>
                            <li>Александр Кокорин</li>
                            <li>Дмитрий Полоз</li>
                        </ul>
                        <div class="clearfix"></div>

                    </div>
                    <div class="col-md-6">
                        <img src="/images/flags/uruguay.svg" alt="">
                        <ul>
                            <li>Главный тренер</li>
                            <li>Хулен Лопетеги</li>
                        </ul>

                        <ul>
                            <li>Стартовый состав</li>
                            <li>Давид де Хеа</li>
                            <li>Хосе Игнасио Начо</li>
                            <li>Хорди Альба</li>
                            <li>Херард Пике</li>
                            <li>Серхио Рамос</li>
                            <li>Серхио Бускетс</li>
                            <li>Тьяго Алькантара</li>
                            <li>Андрес Иньеста</li>
                            <li>Марко Асенсио</li>
                            <li>Сусо</li>
                            <li>Родриго</li>
                        </ul>

                        <ul>
                            <li>Запасные</li>
                            <li>Пепе Рейна</li>
                            <li>Марк Бартра</li>
                            <li>Альваро Арсальюс</li>
                            <li>Альберто Морено</li>
                            <li>Витоло</li>
                            <li>Сауль</li>
                            <li>Асьер Ильяраменди</li>
                            <li>Давид Сильва</li>
                            <li>Луис Альберто</li>
                            <li>Альваро Мората</li>
                            <li>Хосе Кальехон</li>
                            <li>Яго Аспас</li>
                        </ul>

                    </div>
                </div>

            </div>
        </div>


        <div class="row">
            <div class="col-md-12 facts">

                <div class="h-green-square"></div>
                <h2>Интересные факты о командах</h2>


                <div class="row">
                    <div class="col-md-6">
                        <p class="facts-left">
                            Стоимость основного состава: €452 млн<br>
                            Место в рейтинге FIFA: 8-е<br>
                            Зона: UEFA<br>
                            Сколько раз участвовала в ЧМ: 14<br>
                            Лучший результат: чемпион (2010)<br>
                            Главный тренер: Хулен Лопетеги<br>
                            Самый дорогой игрок: Серхио Бускетс (полузащитник, €60 млн)<br>
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p>
                            Стоимость основного состава: €452 млн<br>
                            Место в рейтинге FIFA: 8-е<br>
                            Зона: UEFA<br>
                            Сколько раз участвовала в ЧМ: 14<br>
                            Лучший результат: чемпион (2010)<br>
                            Главный тренер: Хулен Лопетеги<br>
                            Самый дорогой игрок: Серхио Бускетс (полузащитник, €60 млн)<br>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        */?>

    </div>
</div>