<div class="section section-match">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <div class="gazon">
                    <h1>
                        <?php echo $this->cmd1['name_ru']?> <img src="<?php echo $this->cmd1['img']?>" alt="">
                        &mdash;
                        <?php echo $this->cmd2['name_ru']?> <img src="<?php echo $this->cmd2['img']?>" alt="">
                    </h1>
                    <br>
                    <div class="when"><?php echo $this->item['datetime_ru']?></div>
                    <div class="stage">Групповой этап ЧМ-2018</div>
                    <div class="where"><?php echo $this->item['city']?></div>

                    <div class="player-wrapper">
                        <?php if ($this->item['is_now'] or $this->item['is_archive']): ?>

                            <div id="player"></div>

                            <script src="/js/clappr.min.js"></script>

                            <script>
                                $(document).ready(function () {
                                    var player = new Clappr.Player({
                                        parentId: "#player",
    //                                    source: "https://bamper.by/upload/futbik11.mp4",
                                        source: "<?php echo $this->stream_url?>",
                                        width: 600,
                                        height: 339,
                                        autoPlay: true
    //                                    autoPlay: false
                                    });
                                    Clappr.Log.setLevel(0);
                                });
                            </script>

                        <?php endif ?>
                    </div>

                </div>

            </div>
        </div>




    </div>
</div>
