<div class="section section-thumbs">
    <div class="container">
        <div class="row">

            <?php foreach ($this->itemsFuture as $item): ?>
                <div class="col-md-4">
                    <a href="<?php echo $item['url']?>"><img src="/images/fifa-bg.jpg" alt=""></a>
                    <span><a href="<?php echo $item['url']?>"><?php echo $item['cmd1']['name_ru']?> - <?php echo $item['cmd2']['name_ru']?>, <?php echo $item['date_ru']?></a></span>
                </div>
            <?php endforeach ?>

        </div>


    </div>
</div>