<div class="section section-raspisanie">
    <div class="container">
        <div class="row">
            <h1>Расписание матчей</h1>
        </div>
        <div class="row">

            <div class="col-md-12">

                <table class="table">
                    <thead>
                    <tr>
<!--                        <th>Группа</th>-->
<!--                        <th>Тур</th>-->
                        <th>Дата и время</th>
                        <th>Команды</th>
<!--                        <th>Счет</th>-->
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php
                        $dubli = [];
                        foreach ($this->items as $item):
                        if (!$item['is_match']) continue;
                        if (in_array($item['cmd12'], $dubli)) continue;
                        $dubli[] = $item['cmd12'];
                        ?>
                    <tr>
<!--                        <td>Группа А</td>-->
<!--                        <td>1</td>-->
                        <td><?php echo $item['datetime_ru']?></td>
                        <td class="cmd_flags">
                            <img src="<?php echo $item['cmd1']['img']?>" alt="">
                            <?php echo $item['cmd12']?>
                            <img src="<?php echo $item['cmd2']['img']?>" alt="">
                        </td>
<!--                        <td>-:-</td>-->
                        <td>
                            <?php if ($item['is_archive'] AND $item['is_archive_old']): ?>записи нет<?php endif ?>
                            <?php if ($item['is_archive'] AND !$item['is_archive_old']): ?><a href="<?php echo $item['url']?>" class="btn btn-sm btn-primary">Смотреть из архива</a><?php endif ?>
                            <?php if ($item['is_now']): ?><a href="<?php echo $item['url']?>" class="btn btn-sm btn-danger">Смотреть прямую трансляцию</a><?php endif ?>
                            <?php if ($item['is_future']): ?>ждите...<?php endif ?>

                            </a></td>
                    </tr>
                    <?php endforeach ?>

                    </tbody>

                </table>


            </div>

        </div>
    </div>
</div>
