<div class="section section-thumbs">
    <div class="container">
        <div class="row">
            <h1>Расписание матчей</h1>
        </div>
        <div class="row">

            <div class="col-md-12">

                <table class="table">
                    <thead>
                    <tr>
                        <th>Группа</th>
                        <th>Тур</th>
                        <th>Дата,время</th>
                        <th>Команды</th>
                        <th>Счет</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Группа А</td>
                        <td>1</td>
                        <td>14.06.2018, 18:00</td>
                        <td>Россия - Саудовская Аравия</td>
                        <td>-:-</td>
                        <td><a href="#" class="btn btn-sm btn-primary">Смотреть</a></td>
                    </tr>
                    <tr>
                        <td>Группа А</td>
                        <td>1</td>
                        <td>14.06.2018, 18:00</td>
                        <td>Россия - Саудовская Аравия</td>
                        <td>-:-</td>
                        <td><a href="#" class="btn btn-sm btn-primary">Смотреть</a></td>
                    </tr>
                    <tr>
                        <td>Группа А</td>
                        <td>1</td>
                        <td>15.06.2018, 18:00</td>
                        <td>Египет - Уругвай</td>
                        <td>-:-</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Группа А</td>
                        <td>1</td>
                        <td>15.06.2018, 18:00</td>
                        <td>Египет - Уругвай</td>
                        <td>-:-</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Группа А</td>
                        <td>1</td>
                        <td>15.06.2018, 18:00</td>
                        <td>Египет - Уругвай</td>
                        <td>-:-</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Группа А</td>
                        <td>1</td>
                        <td>15.06.2018, 18:00</td>
                        <td>Египет - Уругвай</td>
                        <td>-:-</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Группа А</td>
                        <td>1</td>
                        <td>15.06.2018, 18:00</td>
                        <td>Египет - Уругвай</td>
                        <td>-:-</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Группа А</td>
                        <td>1</td>
                        <td>15.06.2018, 18:00</td>
                        <td>Египет - Уругвай</td>
                        <td>-:-</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Группа А</td>
                        <td>1</td>
                        <td>15.06.2018, 18:00</td>
                        <td>Египет - Уругвай</td>
                        <td>-:-</td>
                        <td></td>
                    </tr>
                    </tbody>

                </table>


            </div>

        </div>
    </div>
</div>
