
<div class="section section-setka">
    <div class="container">

        <h1>Турнирная сетка</h1>



        <h3>Плей-офф</h3>

        <?php foreach ($this->final as $group): ?>
        <div class="row group-row">

            <div class="col-md-6 col-md-offset-3">
                <h2><?php echo $group['h2']?></h2>
                <?php echo $group['resulttable'] ?>
            </div>
        </div>

        <hr>
        <?php endforeach ?>




        <h3>Групповой этап</h3>

        <?php foreach ($this->groups as $group): ?>
            <div class="row group-row">


            <div class="col-sm-6">
                <h2><?php echo $group['h2']?></h2>
                <?php echo $group['grouptable'] ?>
            </div>
            <div class="col-sm-6">
                <h2>Результаты игр</h2>
                <?php echo $group['resulttable'] ?>
            </div>

        </div>

        <hr>
        <?php endforeach ?>

    </div>
</div>

<script>
    $(document).ready(function () {
        $('.group-row a').on('click', function(e){
            e.preventDefault();
            var country = $(this).html().trim();
            if (country)
                window.location.href = '/search/?q=' + country;
        })
    })
</script>