
<div class="section section-setka">
    <div class="container">
        <div class="row">
            <h1>Турнирная сетка</h1>
        </div>
        <div class="row">

            <div class="col-md-12">
                <table class="table">
                    <tbody>
                    <tr>
                        <th class="_group_thead scrollabletable__th__fixed" colspan="4">
                            <div class="sport__table__head">Группа A</div>
                        </th>
                        <th class="">
                            <img src="/images/flags/russia.svg" >
                        </th>
                        <th class="">
                            <img src="/images/flags/saudi-arabia.svg" >
                        </th>
                        <th class="">
                            <img src="/images/flags/egypt.svg" >
                        </th>
                        <th class="">
                            <img src="/images/flags/uruguay.svg" >
                        </th>
                        <th class="_center"><strong>Игры</strong></th>
                        <th class="_center">Победы</th>
                        <th class="_center">Ничьи</th>
                        <th class="_center">Поражения</th>
                        <th class="_center" >Мячи</th>
                        <th class="_center"><strong>Очки</strong></th>
                        <th class="_center">% очков</th>
                    </tr>

                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/russia.svg"></td>
                        <td class="">Россия</td>
                        <td class=""></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>
                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/saudi-arabia.svg"></td>
                        <td class="">Саудовская Аравия</td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>
                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/egypt.svg"></td>
                        <td class="">Египет</td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>
                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/uruguay.svg"></td>
                        <td class="">Уругвай</td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>

                    </tbody>
                </table>
            </div>


            <div class="col-md-12">
                <table class="table">
                    <tbody>
                    <tr>
                        <th class="_group_thead scrollabletable__th__fixed" colspan="4">
                            <div class="sport__table__head">Группа A</div>
                        </th>
                        <th class="">
                            <img src="/images/flags/russia.svg" >
                        </th>
                        <th class="">
                            <img src="/images/flags/saudi-arabia.svg" >
                        </th>
                        <th class="">
                            <img src="/images/flags/egypt.svg" >
                        </th>
                        <th class="">
                            <img src="/images/flags/uruguay.svg" >
                        </th>
                        <th class="_center"><strong>Игры</strong></th>
                        <th class="_center">Победы</th>
                        <th class="_center">Ничьи</th>
                        <th class="_center">Поражения</th>
                        <th class="_center" >Мячи</th>
                        <th class="_center"><strong>Очки</strong></th>
                        <th class="_center">% очков</th>
                    </tr>

                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/russia.svg"></td>
                        <td class="">Россия</td>
                        <td class=""></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>
                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/saudi-arabia.svg"></td>
                        <td class="">Саудовская Аравия</td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>
                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/egypt.svg"></td>
                        <td class="">Египет</td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>
                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/uruguay.svg"></td>
                        <td class="">Уругвай</td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>

                    </tbody>
                </table>
            </div>


            <div class="col-md-12">
                <table class="table">
                    <tbody>
                    <tr>
                        <th class="_group_thead scrollabletable__th__fixed" colspan="4">
                            <div class="sport__table__head">Группа A</div>
                        </th>
                        <th class="">
                            <img src="/images/flags/russia.svg" >
                        </th>
                        <th class="">
                            <img src="/images/flags/saudi-arabia.svg" >
                        </th>
                        <th class="">
                            <img src="/images/flags/egypt.svg" >
                        </th>
                        <th class="">
                            <img src="/images/flags/uruguay.svg" >
                        </th>
                        <th class="_center"><strong>Игры</strong></th>
                        <th class="_center">Победы</th>
                        <th class="_center">Ничьи</th>
                        <th class="_center">Поражения</th>
                        <th class="_center" >Мячи</th>
                        <th class="_center"><strong>Очки</strong></th>
                        <th class="_center">% очков</th>
                    </tr>

                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/russia.svg"></td>
                        <td class="">Россия</td>
                        <td class=""></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>
                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/saudi-arabia.svg"></td>
                        <td class="">Саудовская Аравия</td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>
                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/egypt.svg"></td>
                        <td class="">Египет</td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>
                    <tr data-num="00">
                        <td class="">1</td>
                        <td class=""></td>
                        <td class=""><img src="/images/flags/uruguay.svg"></td>
                        <td class="">Уругвай</td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""><a href="#">–:–</a></td>
                        <td class=""></td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0</td>
                        <td class="">0-0</td>
                        <td class=""><strong>0</strong></td>
                        <td class="">0,0</td>
                    </tr>

                    </tbody>
                </table>
            </div>


        </div>
    </div>
</div>