
<div class="section section-setka">
    <div class="container">
        <div class="row">
            <h1>Турнирная сетка</h1>
        </div>

        <?php foreach ($this->items as $group): ?>
        <div class="row group-row">

            <div class="col-sm-6">
                <h2><?php echo $group['h2']?></h2>
                <?php echo $group['grouptable'] ?>
            </div>
            <div class="col-sm-6">
                <h2>Результаты игр</h2>
                <?php echo $group['resulttable'] ?>
            </div>

        </div>

        <hr>
        <?php endforeach ?>

    </div>
</div>

<script>
    $(document).ready(function () {
        $('.group-row a').on('click', function(e){
            e.preventDefault();
        })
    })
</script>